### ISSUE TITLE
pepk.jar failed to run: Cannot find any provider supporting RSA/NONE/OAEPWithSHA1AndMGF1Padding

### ISSUE THREAD

**Issue by ikool-cn** [yongjhih/pepk#2]
![截图](https://github.com/yongjhih/pepk/assets/4831344/986acb53-cfdc-4485-abed-08a6b340ae5c)

The new version of google play changed **--encryptionkey** to **--encryption-key-path**, when i am run the command,error occurred

```
java -jar pepk.jar --keystore=huoshanbox.jks --alias=huoshanbox --output=output.zip --include-cert --rsa-aes-encryption --encryption-key-path=encryption_public_key.pem

Enter password for store 'huoshanbox.jks':
Enter password for key 'huoshanbox':
Error: Unable to export or encrypt the private key
java.security.NoSuchAlgorithmException: Cannot find any provider supporting RSA/NONE/OAEPWithSHA1AndMGF1Padding
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:563)
	at com.google.wireless.android.vending.developer.signing.tools.extern.export.ExportEncryptedPrivateKeyTool.encryptPrivateKeyWithCkmRsaAesKeyWrapEncryption(ExportEncryptedPrivateKeyTool.java:284)
	at com.google.wireless.android.vending.developer.signing.tools.extern.export.ExportEncryptedPrivateKeyTool.run(ExportEncryptedPrivateKeyTool.java:213)
	at com.google.wireless.android.vending.developer.signing.tools.extern.export.ExportEncryptedPrivateKeyTool.main(ExportEncryptedPrivateKeyTool.java:165)
```
This tool requires jdk 11+,i am tried JDK 11, JDK 17, JDK 20, but got the same error. Which version of jdk should I use?

Help me pls, thanks!

**Comment by Android-LiuHuan** [comment]
Did you solve it? I had the same problem

**Comment by abhisheksisodia** [comment]
Try with OpenJDK 20 version

**Comment by abhisheksisodia** [comment]
Try with OpenJDK 20 version

**Comment by kitkatRC** [comment]
> Try with OpenJDK 20 version

Not effective 
![微信截图_20230903180401](https://github.com/yongjhih/pepk/assets/33120696/a6459a6b-29a5-4c1c-b046-770981f1d63e)

**Comment by Osiris-Team** [comment]
Use OpenJDK (https://jdk.java.net/) instead of the Oracle JDK; they are packaged with different tools, and evidently Google expects the OpenJDK set.

So uninstall your current Java and install a distro like temurin/adoptium that is based on openjdk, which you can download it from here (select msi for windows installer): https://adoptium.net/de/temurin/releases/?os=windows

Original awnser: https://stackoverflow.com/questions/76516045/cannot-find-any-provider-supporting-rsa-none-oaepwithsha1andmgf1padding-when-t

**Comment by mertaksoy** [comment]
I had the same issue. Changed to Open JDK instead of Oracle. Problem fixed ✅
